version: '3.9'
services:
  web:
    image: php:8.2-apache
    container_name: phpapache
    ports:
      - "83:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name : phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: {"IP CasaOS"}
      PMA_PORT: "3306"
